import { Poppins } from "next/font/google";
import "./globals.css";
import ThemeToggle from '@/components/toggletheme'
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Chattrix",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/images/logo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        {children}
        <ThemeToggle/>
      </body>
    </html>
  );
}
